### PR TITLE
Move `StaticArrays` to an extension

### PR DESCRIPTION
**Pull request by jishnub**
This removes the hard dependency on `StaticArrays`, as well as improves package load times.
On master
```julia
julia> @time using LazyArrays
  1.921267 seconds (3.58 M allocations: 330.500 MiB, 5.15% gc time, 0.29% compilation time)
```
This PR
```julia
julia> @time using LazyArrays
  1.333925 seconds (2.38 M allocations: 248.581 MiB, 5.93% gc time)
```
Removing the hard dependency means that one may use this package even when `StaticArrays` is broken (e.g. on nightly).

### CODE REVIEW

**Comment by dlfivefifty** [comment]
But we currently still support Julia v1.6

**Comment by jishnub** [comment]
The behavior on v1.6 (or any version below v1.9) should remain unchanged, as the file is included in the module. The current failure is an Aqua formatting issue that I'll fix.

**Comment by dlfivefifty** [comment]
I don't get how it can work in Julia v1.6 as you are removing it as a dependency in the Project.toml but perhaps I'm missing something

**Comment by jishnub** [comment]
No, that was a mistake on my part, the dependency should be listed (it'll be ignored on recent Julia versions).

**Comment by jishnub** [comment]
Fixed now

**Comment by jishnub** [comment]
Good to merge?

**Pull request merged**
