### PR TITLE
Fix ambiguity `copy(::Mul{<:LazyLayout, <:BandedLayout})`

### LINKED ISSUE #330: Ambiguity `copy(::Mul{<:LazyLayout, <:BandedLayout})`
```julia
julia> using LazyArrays, LinearAlgebra, BandedMatrices

julia> A = UpperTriangular(ApplyArray(inv, rand(5, 5)));

julia> v1, v2 = ApplyVector(+, rand(5), rand(5)), ApplyVector(+, rand(4), rand(4));

julia> B = Tridiagonal(v2, v1, v2);

julia> M = Mul(A, B);

julia> copy(M)
ERROR: MethodError: copy(::Mul{ArrayLayouts.TriangularLayout{'U', 'N', LazyArrays.LazyLayout}, ArrayLayouts.TridiagonalLayout{LazyArrays.LazyLayout, LazyArrays.LazyLayout, LazyArrays.LazyLayout}, UpperTriangular{Float64, ApplyArray{Float64, 2, typeof(inv), Tuple{Matrix{Float64}}}}, Tridiagonal{Float64, ApplyVector{Float64, typeof(+), Tuple{Vector{Float64}, Vector{Float64}}}}}) is ambiguous.

Candidates:
  copy(M::Mul{<:Any, <:Union{ArrayLayouts.HermitianLayout{BandedMatrices.BandedColumns{LazyArrays.LazyLayout}}, ArrayLayouts.SymmetricLayout{BandedMatrices.BandedColumns{LazyArrays.LazyLayout}}, BandedMatrices.BandedColumns{LazyArrays.LazyLayout}, BandedMatrices.BandedRows{LazyArrays.LazyLayout}, LazyArraysBandedMatricesExt.AbstractLazyBandedLayout, ArrayLayouts.BidiagonalLayout{LazyArrays.LazyLayout}, ArrayLayouts.SymTridiagonalLayout{LazyArrays.LazyLayout}, ArrayLayouts.TriangularLayout{UPLO, UNIT, BandedMatrices.BandedColumns{LazyArrays.LazyLayout}} where {UPLO, UNIT}, ArrayLayouts.TriangularLayout{UPLO, UNIT, BandedMatrices.BandedRows{LazyArrays.LazyLayout}} where {UPLO, UNIT}, ArrayLayouts.TridiagonalLayout{LazyArrays.LazyLayout}}})
    @ LazyArraysBandedMatricesExt C:\Users\djv23\.julia\packages\LazyArrays\hpRtS\ext\LazyArraysBandedMatricesExt.jl:550
  copy(M::Mul{<:Union{LazyArrays.AbstractLazyLayout, ArrayLayouts.HermitianLayout{<:LazyArrays.AbstractLazyLayout}, ArrayLayouts.SymmetricLayout{<:LazyArrays.AbstractLazyLayout}, ArrayLayouts.TriangularLayout{'L', 'N', <:LazyArrays.AbstractLazyLayout}, ArrayLayouts.TriangularLayout{'U', 'N', <:LazyArrays.AbstractLazyLayout}, ArrayLayouts.TriangularLayout{'L', 'U', <:LazyArrays.AbstractLazyLayout}, ArrayLayouts.TriangularLayout{'U', 'U', <:LazyArrays.AbstractLazyLayout}}})
    @ LazyArrays C:\Users\djv23\.julia\packages\LazyArrays\hpRtS\src\linalg\mul.jl:360

Possible fix, define
  copy(::Mul{var"#s27", StyleB} where {var"#s27"<:Union{…}, StyleB<:Union{…}})

Stacktrace:
 [1] top-level scope
   @ REPL[15]:1
Some type information was truncated. Use `show(err)` to see complete types.

julia> err
1-element ExceptionStack:
MethodError: copy(::Mul{ArrayLayouts.TriangularLayout{'U', 'N', LazyArrays.LazyLayout}, ArrayLayouts.TridiagonalLayout{LazyArrays.LazyLayout, LazyArrays.LazyLayout, LazyArrays.LazyLayout}, UpperTriangular{Float64, ApplyArray{Float64, 2, typeof(inv), Tuple{Matrix{Float64}}}}, Tridiagonal{Float64, ApplyVector{Float64, typeof(+), Tuple{Vector{Float64}, Vector{Float64}}}}}) is ambiguous.

Candidates:
  copy(M::Mul{<:Any, <:Union{ArrayLayouts.HermitianLayout{BandedMatrices.BandedColumns{LazyArrays.LazyLayout}}, ArrayLayouts.SymmetricLayout{BandedMatrices.BandedColumns{LazyArrays.LazyLayout}}, BandedMatrices.BandedColumns{LazyArrays.LazyLayout}, BandedMatrices.BandedRows{LazyArrays.LazyLayout}, LazyArraysBandedMatricesExt.AbstractLazyBandedLayout, ArrayLayouts.BidiagonalLayout{LazyArrays.LazyLayout}, ArrayLayouts.SymTridiagonalLayout{LazyArrays.LazyLayout}, ArrayLayouts.TriangularLayout{UPLO, UNIT, BandedMatrices.BandedColumns{LazyArrays.LazyLayout}} where {UPLO, UNIT}, ArrayLayouts.TriangularLayout{UPLO, UNIT, BandedMatrices.BandedRows{LazyArrays.LazyLayout}} where {UPLO, UNIT}, ArrayLayouts.TridiagonalLayout{LazyArrays.LazyLayout}}})
    @ LazyArraysBandedMatricesExt C:\Users\djv23\.julia\packages\LazyArrays\hpRtS\ext\LazyArraysBandedMatricesExt.jl:550
  copy(M::Mul{<:Union{LazyArrays.AbstractLazyLayout, ArrayLayouts.HermitianLayout{<:LazyArrays.AbstractLazyLayout}, ArrayLayouts.SymmetricLayout{<:LazyArrays.AbstractLazyLayout}, ArrayLayouts.TriangularLayout{'L', 'N', <:LazyArrays.AbstractLazyLayout}, ArrayLayouts.TriangularLayout{'U', 'N', <:LazyArrays.AbstractLazyLayout}, ArrayLayouts.TriangularLayout{'L', 'U', <:LazyArrays.AbstractLazyLayout}, ArrayLayouts.TriangularLayout{'U', 'U', <:LazyArrays.AbstractLazyLayout}}})
    @ LazyArrays C:\Users\djv23\.julia\packages\LazyArrays\hpRtS\src\linalg\mul.jl:360

Possible fix, define
  copy(::Mul{var"#s27", StyleB} where {var"#s27"<:Union{LazyArrays.AbstractLazyLayout, ArrayLayouts.HermitianLayout{<:LazyArrays.AbstractLazyLayout}, ArrayLayouts.SymmetricLayout{<:LazyArrays.AbstractLazyLayout}, ArrayLayouts.TriangularLayout{'L', 'N', <:LazyArrays.AbstractLazyLayout}, ArrayLayouts.TriangularLayout{'U', 'N', <:LazyArrays.AbstractLazyLayout}, ArrayLayouts.TriangularLayout{'L', 'U', <:LazyArrays.AbstractLazyLayout}, ArrayLayouts.TriangularLayout{'U', 'U', <:LazyArrays.AbstractLazyLayout}}, StyleB<:Union{ArrayLayouts.HermitianLayout{BandedMatrices.BandedColumns{LazyArrays.LazyLayout}}, ArrayLayouts.SymmetricLayout{BandedMatrices.BandedColumns{LazyArrays.LazyLayout}}, BandedMatrices.BandedColumns{LazyArrays.LazyLayout}, BandedMatrices.BandedRows{LazyArrays.LazyLayout}, LazyArraysBandedMatricesExt.AbstractLazyBandedLayout, ArrayLayouts.BidiagonalLayout{LazyArrays.LazyLayout}, ArrayLayouts.SymTridiagonalLayout{LazyArrays.LazyLayout}, ArrayLayouts.TriangularLayout{UPLO, UNIT, BandedMatrices.BandedColumns{LazyArrays.LazyLayout}} where {UPLO, UNIT}, ArrayLayouts.TriangularLayout{UPLO, UNIT, BandedMatrices.BandedRows{LazyArrays.LazyLayout}} where {UPLO, UNIT}, ArrayLayouts.TridiagonalLayout{LazyArrays.LazyLayout}}})

Stacktrace:
 [1] top-level scope
   @ REPL[15]:1
```

### PR DESCRIPTION
**Pull request by DanielVandH**
Fixes #330

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Can you fix the code cob?

**Comment by DanielVandH** [comment]
Ah, the BandedMatrices extension wasn't loaded so the ambiguity hadn't been introduced yet. Should be fixed now

**Comment by DanielVandH** [comment]
Or not. I'll look into the remaining issues soon.

**Comment by DanielVandH** [comment]
CI needs https://github.com/JuliaLinearAlgebra/ArrayLayouts.jl/pull/240

**Comment by DanielVandH** [comment]
Not sure what the issue is with that line identified by codecov but I don't think it's related. Should be ok now

**Pull request merged**
