### PR TITLE
Add Hcat * Vcat special case

### PR DESCRIPTION
**Pull request by dlfivefifty**
Starts to address https://github.com/JuliaArrays/LazyArrays.jl/issues/48

@antoine-levitt This should give an idea on what to do. At this point just overloading
```julia
materialize!(::MatMulMatAdd{<:VcatLayout,<:HcatLayout})
```
should suffice.

### CODE REVIEW

**Comment by antoine-levitt** [comment]
Thanks! I was just looking at this.

**Comment by antoine-levitt** [comment]
I assume we also need something to support products of cats and regular matrices? Or is that magically covered?

**Comment by dlfivefifty** [comment]
It will fall back to the slow default, but something like the following should be fast for Hcat * Strided (e.g. Hcat * Vector):
```julia
function materialize!(M::MatMulVecAdd{<:HcatLayout})
    α,A,B,β,C =  M.α,M.A,M.B,M.β,M.C
    T = eltype(C)
    _fill_lmul!(β,C) # this is temporary until strong β = false is supported
    ind = 0
    for a in A.arrays
        jr = ind+1:ind+size(a,2)
        b = view(B, jr, :) 
        materialize!(MulAdd(α,a,b,one(T),C))
        ind = last(jr)
    end
    C
 end
```

**Comment by antoine-levitt** [comment]
OK, thanks! Will try to do the 3^2 combinations with Hcat,Vcat and dense.

**Comment by dlfivefifty** [comment]
I think you only need 4, not 3^2: ` Hcat * Vcat `, ` Vcat * Hcat `, ` Vcat * any `, ` Hcat * any `. This is because I don’t think ` Vcat * Vcat ` or ` Hcat * Hcat ` are that useful....

(Ok each will need to be done three times, once for matrix * matrix, matrix * vector and vector * matrix...)

**Pull request merged**
