### PR TITLE
Accelerate `_mul_ApplyStyle`

### PR DESCRIPTION
**Pull request by putianyi889**
Before:
```julia
julia> @time ApplyArray(*, [ones(10,10) for k in 1:25]...);
105.543375 seconds (92.57 M allocations: 3.603 GiB, 1.06% gc time, 0.35% compilation time)
```

After:
```julia
julia> @time ApplyArray(*, [ones(10,10) for k in 1:25]...);
  0.163698 seconds (52.06 k allocations: 3.539 MiB, 98.30% compilation time)

julia> @time ApplyArray(*, [ones(10,10) for k in 1:200]...);
  1.248202 seconds (660.75 k allocations: 48.919 MiB, 8.38% gc time, 97.46% compilation time)
```

Also happens to solve #255 

Note that the compilation time will always kick in.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Amazing, thanks for this!!

**Comment by dlfivefifty** [comment]
Oh wait it’s doing things at run time. I think we should make it a generated function to do this at compile time

**Comment by putianyi889** [comment]
I had thought about that for a while but couldn't come up with an idea.

**Comment by putianyi889** [comment]
alright, just adding `@generated` does the job.

One-line recursion:
```julia
julia> using LazyArrays

julia> A=[ones(10,10) for k in 1:500];

julia> @time ApplyArray(*, A...);
 28.553755 seconds (2.82 M allocations: 549.886 MiB, 0.82% gc time, 99.56% compilation time)

julia> @time ApplyArray(*, A...);
  0.087592 seconds (10.59 k allocations: 6.566 MiB)

julia> B=A[1:200];

julia> @time ApplyArray(*, B...);
  4.429628 seconds (125.22 k allocations: 27.461 MiB, 0.63% gc time, 99.54% compilation time)

julia> @time ApplyArray(*, B...);
  0.016024 seconds (4.29 k allocations: 1.219 MiB)
```

$O(n^2)$ algorithm:
```julia
julia> using LazyArrays
[ Info: Precompiling LazyArrays [5078a376-72f3-5289-bfd5-ec5146d43c02]

julia> A=[ones(10,10) for k in 1:500];

julia> @time ApplyArray(*, A...);
  4.793488 seconds (2.13 M allocations: 172.483 MiB, 1.48% gc time, 97.39% compilation time)

julia> @time ApplyArray(*, A...);
  0.085763 seconds (10.59 k allocations: 6.566 MiB)

julia> B=A[1:200];

julia> @time ApplyArray(*, B...);
  0.645032 seconds (53.70 k allocations: 3.771 MiB, 96.96% compilation time)

julia> @time ApplyArray(*, B...);
  0.016678 seconds (4.29 k allocations: 1.219 MiB)
```

**Comment by dlfivefifty** [comment]
I don't understand how this is working: your implementation of `_mul_ApplyStyle` doesn't actually return anything?

**Comment by putianyi889** [comment]
the last assignment which is list[1] is returned

**Comment by putianyi889** [comment]
it was a mistake... I have no idea why nothing went wrong

**Comment by putianyi889** [comment]
can you approve the workflows? @dlfivefifty

**Comment by dlfivefifty** [comment]
Can you add tests with `@inferred` and `@allocated` to make sure we are actually doing things at compile-time?

You can confirm this yourself as well using `@code_warntype ApplyStyle(*, a, b)`, which will just return the applystyle with no actual code

**Comment by putianyi889** [comment]
I don't understand how they work. If they take run-time, will `@inferred` throw an error? what about `@allocated`?

**Comment by dlfivefifty** [comment]
Since the only thing it actually is computing is a return type, by definition of the code is inferred then its doing everything at compile time. 


```julia
julia> @inferred(ApplyStyle(*, A, A))
LazyArrays.DefaultArrayApplyStyle()
```

The allocations is just a sanity check but they are too unreliable so forget that. Just add some `@inferred` to some `ApplyStyle` calls and that should be enough.

**Comment by dlfivefifty** [comment]
ignore codecov since its just because generated functions are trackable

**Comment by putianyi889** [comment]
Is that enough?

**Comment by dlfivefifty** [comment]
I'll merge this once tests pass.

If you want a PR tagged remember to bump the version number

**Comment by putianyi889** [comment]
version bumped

**Pull request merged**
